### PR TITLE
added models

### PR DESCRIPTION
**Pull request by jere-mie**
### What are you trying to accomplish?
Add simple models to the site

### How are you accomplishing it?
Create model files

### Is there anything reviewers should know?
- Currently we're storing discord uids as ints, but it might make more sense to store as strings considering how big they are.
- I currently have all date/time fields appearing as strings in the models. Not sure what the best solution for that is in golang so I'm open to suggestions
- I removed the created_at and deleted_at fields of each table. I'm guessing they just come by default with rails or smth. If we think these are useful though we can add them back
- Should we consider doing logical deletion rather than hard deletion? IE, have an "isArchived" or "isDeleted" column and to "delete" a record you just flip the value in that column.
- I removed all of the hunt and some of the other unused stuff. I figured we're almost definitely not going to be using any of it.
- If there are any best practices I didn't follow lmk (for example, to use or not to use underscores in field names)

- [x] Is it safe to rollback this change if anything goes wrong?

### CODE REVIEW

**Review by prairir — COMMENTED** [review]
Are all of these meant to be package visible only?

**Comment by jere-mie** [comment]
Oh shoot probably not, lemme guess I need them to be upper cased? @prairir

**Comment by prairir** [comment]
> Oh shoot probably not, lemme guess I need them to be upper cased? @prairir

Yeah it needs to be uppercased

**Comment by jere-mie** [comment]
Gotta love go lol

**Review by prairir — APPROVED** [review]

**Pull request merged**
